-- Migration: 1 TOKEN = 1 PESQUISA = 10 RESULTADOS
-- weekly_limit and monthly_limit now represent TOKENS (actions), not raw results.
-- 1 search = 1 token consumed. 1 "Ver Mais" click = 1 token consumed.
-- Each token delivers 10 results to the user.
--
-- The full consume_search_token rewrite with plan-aware reset logic
-- is applied in the subsequent migration: 20260320000001.
--
-- Existing users on free plan should be updated manually in Supabase:
--   UPDATE search_quotas SET weekly_limit = 1, monthly_limit = 0
--   WHERE plan_type = 'free';
